[book]
title = "넷평의 Clojurescript 노트"
description = "study.clojurescript"
authors = ["netpyoung"]
language = "kr"
multilingual = false
src = "src"

[output.html]
no-section-label = true
site-url = "/study.clojurescript/"
git-repository-url = "https://github.com/netpyoung/study.clojurescript"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/netpyoung/study.clojurescript/edit/main/{path}"
